# SPDX-FileCopyrightText: Copyright Oleksii Samoliuk
# SPDX-License-Identifier: MIT
---
- name: "Checking correctness the ssm_prefixes.{{ item.name }}"
  ansible.builtin.fail:
    msg: "Value 'prefix' or 'name' is not defined for ssm_prefixes.{{ item }}"
  when: item.prefix is not defined or item.name is not defined

- name: "Gathering values from AWS SSM Parameters Store by prefix {{ item.prefix }}"
  ansible.builtin.set_fact:
    "{{ item.name }}_aws_ssm": "{{ lookup('amazon.aws.aws_ssm', '{{ item.prefix }}', shortnames=true, bypath=true, recursive=true) }}"
  when: (item.prefix is defined and item.name is defined) and
        (item.prefix | length>0 and item.name | length>0)
